In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\iamin\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\iamin\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\iamin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\iamin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\iamin\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\iamin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\iamin\anaconda3\lib\site-packages (1.26.4)

In [5]:
import pandas as pd
import numpy as np

In [6]:
yanki_df = pd.read_csv(r'dataset\cleaneddata\yanki_ecommerce.csv')

In [7]:
yanki_df.tail()

,Order_ID,Customer_ID,Customer_Name,Product_ID,Product_Name,Brand,Category,Price,Quantity,Total_Price,Order_Date,Shipping_Address,City,State,Country,Postal_Code,Email,Phone_Number,Payment_Method,Transaction_Status
1015,bb17468a-7648-4974-b3d6-9f9f1a78cb39,1e75eb3a-9ba5-4ea6-82ec-886abe298058,Jeremy Farrell,ad5204d7-e5c2-417c-91f7-5fa07619ef54,officer,Thornton Group,perfume,118.46,3,355.38,2023-08-07 12:34:10.009932,"440 Carson Port Suite 634\nLake Heather, MA 22883",West Danielle,South Carolina,Iran,17863,leejohn@example.com,922.207.8157x85481,PayPal,pending
1016,184827be-c3bd-40a1-a2bb-8b085d58ddc0,c53c32ef-2e64-4ac4-ac48-3707ab1ebd1f,Marc Hudson,0ea15074-b823-4345-924c-aeb9fafe9571,treat,Guzman-Petersen,perfume,91.14,2,182.28,2024-01-14 09:27:21.372714,"75333 Clayton Forges Apt. 292\nLake Matthew, D...",Whitemouth,Arkansas,Japan,24756,james85@example.org,908.901.4896x12666,PayPal,completed
1017,2dac83f2-fddb-4761-b211-ea716feee91c,ebc19a03-a32d-4d3c-9976-f30cee3d3a70,Devin Joseph,e911b0a9-75fb-4c17-b552-52be0d19f856,watch,Jones-May,perfume,246.73,10,2467.30,2021-01-23 10:25:25.233434,"426 Amy Islands\nCollinsberg, MT 21928",South Stephanie,Indiana,Timor-Leste,54502,chadbenson@example.com,(718)789-6289,PayPal,pending
1018,08341169-2d82-41d4-8273-fda624f99042,0598403f-7a42-44a9-994e-9f23feb20394,Spencer Elliott,9c9792f9-4dc2-43b2-98f4-e989cf1bdb3a,toward,Richardson PLC,perfume,647.26,10,6472.60,2022-04-15 23:15:41.204791,"01490 Lopez Garden\nPort Adamton, ND 35200",Thompsonfort,South Dakota,Pakistan,78892,eric98@example.org,366-506-0469x728,PayPal,pending
1019,476f789e-727f-4aad-9395-3d66aec6261a,8832dd24-c104-475b-8327-d687d3912b58,Jeffrey Jackson,b835cfa0-70c5-4018-a5e8-50c9d71b5d56,hit,Hamilton-Daniels,perfume oil,350.29,3,1050.87,2021-04-01 09:23:59.544167,"875 Duarte Knolls\nGarciamouth, TX 16464",Jonathanport,Utah,Western Sahara,26856,turnerjoanna@example.org,8483263716,Credit Card,pending

In [8]:
yanki_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            1000 non-null   object
 1   Customer_ID         1000 non-null   object
 2   Customer_Name       1000 non-null   object
 3   Product_ID          1020 non-null   object
 4   Product_Name        1020 non-null   object
 5   Brand               1020 non-null   object
 6   Category            1020 non-null   object
 7   Price               1020 non-null   float64
 8   Quantity            1020 non-null   int64
 9   Total_Price         1020 non-null   float64
 10  Order_Date          1020 non-null   object
 11  Shipping_Address    1020 non-null   object
 12  City                1020 non-null   object
 13  State               1020 non-null   object
 14  Country             1020 non-null   object
 15  Postal_Code         1020 non-null   int64
 16  Email               1020 non-null   object
 17  Phone_Number        1020 non-null   object
 18  Payment_Method      1020 non-null   object
 19  Transaction_Status  1020 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 159.5+ KB

DATA CLEANING AND TRANSFORMATION

In [9]:
yanki_df.dropna(subset= ['Order_ID', 'Customer_ID'], inplace= True)

In [10]:
yanki_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 2 to 1019
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            1000 non-null   object
 1   Customer_ID         1000 non-null   object
 2   Customer_Name       1000 non-null   object
 3   Product_ID          1000 non-null   object
 4   Product_Name        1000 non-null   object
 5   Brand               1000 non-null   object
 6   Category            1000 non-null   object
 7   Price               1000 non-null   float64
 8   Quantity            1000 non-null   int64
 9   Total_Price         1000 non-null   float64
 10  Order_Date          1000 non-null   object
 11  Shipping_Address    1000 non-null   object
 12  City                1000 non-null   object
 13  State               1000 non-null   object
 14  Country             1000 non-null   object
 15  Postal_Code         1000 non-null   int64
 16  Email               1000 non-null   object
 17  Phone_Number        1000 non-null   object
 18  Payment_Method      1000 non-null   object
 19  Transaction_Status  1000 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 164.1+ KB

In [11]:
yanki_df['Order_Date'] = pd.to_datetime(yanki_df['Order_Date'])

In [12]:
yanki_df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price', 'Quantity', 'Total_Price',
       'Order_Date', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code', 'Email', 'Phone_Number', 'Payment_Method',
       'Transaction_Status'],
      dtype='object')

In [13]:
Customer_df = yanki_df[['Customer_ID', 'Customer_Name','Email', 'Phone_Number']].copy().drop_duplicates().reset_index(drop=True)

In [14]:
Customer_df

,Customer_ID,Customer_Name,Email,Phone_Number
0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,Dominic Buchanan,margaret97@example.com,259.603.6134
1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,Daniel Allen,angela55@example.com,+1-869-659-4272x982
2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,Daniel Schmidt,wayne59@example.org,292.840.0975x724
3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,John Gonzalez,qsherman@example.com,+1-643-561-3912x262
4,81b513ad-5c02-48cf-bff0-39e1440c4d22,Amber Benitez,derek85@example.com,3424148376
...,...,...,...,...
985,1e75eb3a-9ba5-4ea6-82ec-886abe298058,Jeremy Farrell,leejohn@example.com,922.207.8157x85481
986,c53c32ef-2e64-4ac4-ac48-3707ab1ebd1f,Marc Hudson,james85@example.org,908.901.4896x12666
987,ebc19a03-a32d-4d3c-9976-f30cee3d3a70,Devin Joseph,chadbenson@example.com,(718)789-6289
988,0598403f-7a42-44a9-994e-9f23feb20394,Spencer Elliott,eric98@example.org,366-506-0469x728
989,8832dd24-c104-475b-8327-d687d3912b58,Jeffrey Jackson,turnerjoanna@example.org,8483263716

In [15]:
products_df = yanki_df[['Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price']].copy().drop_duplicates().reset_index(drop=True)

In [16]:
products_df.tail()

,Product_ID,Product_Name,Brand,Category,Price
985,ad5204d7-e5c2-417c-91f7-5fa07619ef54,officer,Thornton Group,perfume,118.46
986,0ea15074-b823-4345-924c-aeb9fafe9571,treat,Guzman-Petersen,perfume,91.14
987,e911b0a9-75fb-4c17-b552-52be0d19f856,watch,Jones-May,perfume,246.73
988,9c9792f9-4dc2-43b2-98f4-e989cf1bdb3a,toward,Richardson PLC,perfume,647.26
989,b835cfa0-70c5-4018-a5e8-50c9d71b5d56,hit,Hamilton-Daniels,perfume oil,350.29

In [17]:
shipping_df = yanki_df[['Customer_ID','Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code']].copy().drop_duplicates().reset_index(drop = True)

In [18]:
shipping_df

,Customer_ID,Shipping_Address,City,State,Country,Postal_Code
0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,"PSC 2224, Box 2284\nAPO AP 65880",Jordanborough,Arkansas,Kuwait,27879
1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,"83909 Johnson Mall\nTranberg, MS 99017",Lake Ginatown,Georgia,Saint Vincent and the Grenadines,39336
2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,"82101 Johnson Flat\nWest Ryan, MS 29075",Sarahville,Ohio,France,30845
3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,"4542 Gary Lane\nSouth Alexander, VI 27671",Lake Michelle,Arkansas,Sao Tome and Principe,30955
4,81b513ad-5c02-48cf-bff0-39e1440c4d22,"6794 Caroline Crescent\nEast Karlside, GU 81379",Olsenville,Mississippi,Croatia,45429
...,...,...,...,...,...,...
985,1e75eb3a-9ba5-4ea6-82ec-886abe298058,"440 Carson Port Suite 634\nLake Heather, MA 22883",West Danielle,South Carolina,Iran,17863
986,c53c32ef-2e64-4ac4-ac48-3707ab1ebd1f,"75333 Clayton Forges Apt. 292\nLake Matthew, D...",Whitemouth,Arkansas,Japan,24756
987,ebc19a03-a32d-4d3c-9976-f30cee3d3a70,"426 Amy Islands\nCollinsberg, MT 21928",South Stephanie,Indiana,Timor-Leste,54502
988,0598403f-7a42-44a9-994e-9f23feb20394,"01490 Lopez Garden\nPort Adamton, ND 35200",Thompsonfort,South Dakota,Pakistan,78892
989,8832dd24-c104-475b-8327-d687d3912b58,"875 Duarte Knolls\nGarciamouth, TX 16464",Jonathanport,Utah,Western Sahara,26856

***Resetting Index***

In [102]:
shipping_df.index.name = 'Shipping_ID'
shipping_df.reset_index()

,Shipping_ID,Customer_ID,Shipping_Address,City,State,Country,Postal_Code
0,0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,"PSC 2224, Box 2284\nAPO AP 65880",Jordanborough,Arkansas,Kuwait,27879
1,1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,"83909 Johnson Mall\nTranberg, MS 99017",Lake Ginatown,Georgia,Saint Vincent and the Grenadines,39336
2,2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,"82101 Johnson Flat\nWest Ryan, MS 29075",Sarahville,Ohio,France,30845
3,3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,"4542 Gary Lane\nSouth Alexander, VI 27671",Lake Michelle,Arkansas,Sao Tome and Principe,30955
4,4,81b513ad-5c02-48cf-bff0-39e1440c4d22,"6794 Caroline Crescent\nEast Karlside, GU 81379",Olsenville,Mississippi,Croatia,45429
...,...,...,...,...,...,...,...
985,985,1e75eb3a-9ba5-4ea6-82ec-886abe298058,"440 Carson Port Suite 634\nLake Heather, MA 22883",West Danielle,South Carolina,Iran,17863
986,986,c53c32ef-2e64-4ac4-ac48-3707ab1ebd1f,"75333 Clayton Forges Apt. 292\nLake Matthew, D...",Whitemouth,Arkansas,Japan,24756
987,987,ebc19a03-a32d-4d3c-9976-f30cee3d3a70,"426 Amy Islands\nCollinsberg, MT 21928",South Stephanie,Indiana,Timor-Leste,54502
988,988,0598403f-7a42-44a9-994e-9f23feb20394,"01490 Lopez Garden\nPort Adamton, ND 35200",Thompsonfort,South Dakota,Pakistan,78892
989,989,8832dd24-c104-475b-8327-d687d3912b58,"875 Duarte Knolls\nGarciamouth, TX 16464",Jonathanport,Utah,Western Sahara,26856

In [20]:
yanki_df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price', 'Quantity', 'Total_Price',
       'Order_Date', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code', 'Email', 'Phone_Number', 'Payment_Method',
       'Transaction_Status'],
      dtype='object')

In [21]:
order_df = yanki_df[['Order_ID','Customer_ID','Product_ID', 'Quantity', 'Total_Price','Order_Date']].copy().drop_duplicates().reset_index(drop=True)

In [22]:
order_df.head(20)

,Order_ID,Customer_ID,Product_ID,Quantity,Total_Price,Order_Date
0,e32af09a-b6ab-497e-af3a-331e4d4ed6e7,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,2ef6e8fa-6a36-4515-b1c2-a0a700abf386,2,501.14,2020-03-06 06:49:07.272117
1,86eb8859-14ab-4d4e-9267-c5826f4e0c8e,fa3ca35a-5540-404b-a7eb-9001cdcbd840,3ba38e01-f8e7-4af2-9246-87ef0961d4f5,6,1078.86,2020-07-31 07:09:30.231510
2,7379b560-8897-4623-92a2-523ddcdc43a1,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,a58c53bd-a34b-4541-b926-bec9eb84cac2,7,4203.85,2021-05-11 04:33:09.707443
3,30c57f86-2fed-43c0-a399-654c2c3bb18d,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,e6021be5-90be-4199-b6c6-82542fb2973c,9,3729.24,2023-09-12 01:47:56.290477
4,41c29d81-9622-43c1-b537-7cdb320d3e6a,81b513ad-5c02-48cf-bff0-39e1440c4d22,60127671-ab32-4fb5-bfeb-1a7782ad835e,9,6336.45,2021-08-20 18:02:04.254156
5,0b8915d7-0614-47c4-88be-25aae8fa477b,7f6608ca-b11e-497f-9421-34ee62f9e220,0d1b37a3-8159-4e28-841b-06971fe73e28,7,6661.83,2020-05-08 13:26:10.974298
6,5f05f9e8-57c3-4610-bc41-3c2ccbe3e783,de08452f-8820-4b7e-a394-dba5520a9ce7,9e82b85c-d4d6-4235-91f1-137fb41529ca,1,688.47,2022-10-23 08:26:37.744590
7,0abf28e1-7a76-47d5-9d66-2fe2ca920fda,e1ef782d-6bd8-4880-ae57-f6638c7309fc,48ba3e86-167d-4b02-a5e8-0885e946edcb,4,2419.28,2022-06-27 22:14:28.996406
8,73129f55-e6fd-45b1-a3ac-fef5fae85dd7,df6652a7-8923-431c-b49b-f57138dc1130,74416f33-d5da-409c-b483-ac019b19f5c3,5,4395.90,2021-02-02 11:44:28.581746
9,17647c6b-d1cc-4c86-a1d1-b06641de1574,ef9962f3-cfbe-470e-a6ad-d285dbbfa54b,69caf9a6-a313-489d-a21e-1bcab6ea430e,6,5067.90,2020-07-12 19:08:58.490900
10,a16962fd-0ae2-45cd-bc79-bb5c8fc3c76c,2a5aa693-90a5-487d-bed5-709577862299,2009dc42-c675-48f2-aef9-b3a86556d508,5,4485.60,2022-04-28 10:05:39.466906
11,444dee20-f3e7-4a46-94bf-86f28f3218db,6c01445d-e4d3-4560-99ee-4a377d042353,d47180ed-6607-4dd0-a521-303b187bfeb3,10,4545.50,2020-10-21 20:51:49.100957
12,2bad61d7-1e00-4280-9c63-851860da9097,ca0d091c-0d3d-4d01-a4c9-85f07e01f2f5,d96c5a13-1fbd-43a3-bcfc-83f5b139403b,5,3152.65,2021-03-29 14:41:32.246132
13,f4ca896e-9500-4cad-830b-1d4c264d2e17,3642f2c6-9513-4258-851a-1ca383020a5e,0a59ce14-fd99-4ded-bd19-4b22a52543fa,4,2968.64,2024-02-05 03:13:39.247584
14,7b10e89e-29e2-49df-951b-cb69f5d63fd7,d345f895-73fe-4d1f-9119-090e3e22cf40,152d1d94-2f29-4bd0-a1c7-8e3489a65c0f,9,7182.27,2022-03-25 05:25:06.103400
15,596d5762-2de9-4c0f-aa7c-7e6eefefb2fb,105dedd4-90ce-48ab-8993-d206ca55f9e4,82a088c5-b4be-4e1c-90d5-5fd8c20080fe,4,970.96,2020-08-16 03:15:33.290679
16,4e830cf0-ea4b-451d-b5ed-753db1dfe1fc,e919ab84-fdc0-4e10-938d-56418db183ab,273e9342-c3f2-47b0-b00d-81cfe7c77be9,4,2710.16,2020-09-04 21:52:30.900782
17,0e137c97-97a6-4818-848b-de4c93238bb7,d6e4e518-cf57-443a-bd52-6e86fbcc566e,b4ff33f4-c0c5-44fa-b179-25968b3c803b,1,21.98,2022-01-17 19:49:51.277135
18,069722e1-6803-47af-9c47-b07bc05c7671,766c89fa-2f04-4e88-b81a-732161a8c8cc,0e4bdf71-b57c-455d-bc95-375f945af521,7,6235.81,2020-04-08 13:12:59.128325
19,5c3f5e4c-676e-4223-b23d-74e93cb85325,1a547842-3a19-4957-bfd0-47957f49d7ac,ff4c2f8f-fec1-4b20-9de3-12e0cbc57993,2,587.00,2022-02-06 15:37:47.100947

In [23]:
payment_df = yanki_df[['Order_ID','Phone_Number', 'Payment_Method',
       'Transaction_Status']].copy().drop_duplicates().reset_index(drop= True)

In [24]:
payment_df.head(10)

,Order_ID,Phone_Number,Payment_Method,Transaction_Status
0,e32af09a-b6ab-497e-af3a-331e4d4ed6e7,259.603.6134,Debit Card,completed
1,86eb8859-14ab-4d4e-9267-c5826f4e0c8e,+1-869-659-4272x982,Credit Card,completed
2,7379b560-8897-4623-92a2-523ddcdc43a1,292.840.0975x724,PayPal,pending
3,30c57f86-2fed-43c0-a399-654c2c3bb18d,+1-643-561-3912x262,PayPal,completed
4,41c29d81-9622-43c1-b537-7cdb320d3e6a,3424148376,PayPal,pending
5,0b8915d7-0614-47c4-88be-25aae8fa477b,833-392-3750x99267,Debit Card,pending
6,5f05f9e8-57c3-4610-bc41-3c2ccbe3e783,824-668-9191,PayPal,completed
7,0abf28e1-7a76-47d5-9d66-2fe2ca920fda,+1-683-714-3681,PayPal,completed
8,73129f55-e6fd-45b1-a3ac-fef5fae85dd7,+1-261-681-8748x0788,PayPal,completed
9,17647c6b-d1cc-4c86-a1d1-b06641de1574,+1-269-289-6161,PayPal,completed

In [25]:
# Saving files

In [26]:
payment_df.to_csv(r'C:\Users\iamin\OneDrive\Desktop\yanki_ecommerce\Yanki_eCommerce\dataset\cleaneddata\ Payment.csv', index= False)
Customer_df.to_csv(r'C:\Users\iamin\OneDrive\Desktop\yanki_ecommerce\Yanki_eCommerce\dataset\cleaneddata\ Customer.csv', index= False)
order_df.to_csv(r'C:\Users\iamin\OneDrive\Desktop\yanki_ecommerce\Yanki_eCommerce\dataset\cleaneddata\ Orders.csv', index= False)
shipping_df.to_csv(r'C:\Users\iamin\OneDrive\Desktop\yanki_ecommerce\Yanki_eCommerce\dataset\cleaneddata\ Shipping_Details.csv', index= False)
products_df.to_csv(r'C:\Users\iamin\OneDrive\Desktop\yanki_ecommerce\Yanki_eCommerce\dataset\cleaneddata\ Products.csv', index= False)

**Creating a DataBase for Postgres**

In [27]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in c:\users\iamin\anaconda3\lib\site-packages (2.9.9)

In [28]:
import psycopg2

In [29]:
def db_connection():
    connection = psycopg2.connect(
        host='localhost',
        database ='Yanki_eCommerce',
        user = 'postgres',
        password = 'root'

    )
    return connection

In [30]:
conn = db_connection()

### Creating sql tables

In [54]:
def create_tables():
    conn = db_connection()
    cursor = conn.cursor()
    create_table_query = '''
                                CREATE SCHEMA IF NOT EXISTS yanki;

                                DROP TABLE IF EXISTS yanki.customers CASCADE;
                                DROP TABLE IF EXISTS yanki.products CASCADE;
                                DROP TABLE IF EXISTS yanki.orders CASCADE;
                                DROP TABLE IF EXISTS yanki.payment_method CASCADE;
                                DROP TABLE IF EXISTS yanki.shipping CASCADE;
                                

                                CREATE TABLE IF NOT EXISTS yanki.customers(
                                Customer_ID UUID Primary Key,
                                Customer_Name TEXT,
                                Email TEXT,
                                Phone TEXT
                                );

                                CREATE TABLE IF NOT EXISTS yanki.products(
                                Product_ID UUID Primary Key,
                                Product_Name TEXT,
                                Brand TEXT,
                                Category TEXT,
                                Price FLOAT
                                );

                                CREATE TABLE IF NOT EXISTS yanki.Shipping(
                                Shipping_ID Serial Primary Key,
                                Customer_ID UUID,
                                Shipping_Address TEXT,
                                City TEXT,
                                State TEXT,
                                Country TEXT,
                                Postal_Code INTEGER,
                                Foreign Key (Customer_ID)references yanki.customers(Customer_ID)
                                );
                                
                                CREATE TABLE IF NOT EXISTS yanki.orders(
                                Order_ID UUID Primary Key,
                                Customer_ID UUID ,
                                Product_ID UUID,
                                Quantity INTEGER,
                                Total_Price Float,
                                Order_Date Date,

                                Foreign Key (Customer_ID)references yanki.customers(Customer_ID),
                                Foreign Key (Product_ID)references yanki.products(Product_ID)
                                );

                                CREATE TABLE IF NOT EXISTS yanki.payment(
                                Order_ID UUID Primary Key,
                                Phone_Number TEXT,
                                Payment_Method TEXT,
                                Transaction_Status TEXT,
                                
                                Foreign Key (Order_ID)references yanki.orders(Order_ID)
                               
                                );'''
    cursor.execute(create_table_query)
    conn.commit()
    cursor.close()
    conn.close()

In [41]:
display(payment_df.columns)

Index(['Order_ID', 'Phone_Number', 'Payment_Method', 'Transaction_Status'], dtype='object')

In [42]:
display(payment_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order_ID            990 non-null    object
 1   Phone_Number        990 non-null    object
 2   Payment_Method      990 non-null    object
 3   Transaction_Status  990 non-null    object
dtypes: object(4)
memory usage: 31.1+ KB

None

In [53]:
yanki_df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'Product_ID',
       'Product_Name', 'Brand', 'Category', 'Price', 'Quantity', 'Total_Price',
       'Order_Date', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code', 'Email', 'Phone_Number', 'Payment_Method',
       'Transaction_Status'],
      dtype='object')

In [55]:
create_tables()

In [80]:
import csv
def load_data(csv_path):
    conn = db_connection()
    cursor = conn.cursor()
    with open(csv_path, 'r') as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                           INSERT INTO yanki.customers(Customer_ID, Customer_Name, Email, Phone)
                            VALUES (%s,%s,%s,%s);''',
                            row
                           
                           
                        )
    conn.commit()
    cursor.close()
    conn.close()
    
csv_file_path = r'C:\Users\iamin\OneDrive\Desktop\yanki_ecommerce\Yanki_eCommerce\dataset\cleaneddata\ Customer.csv'
load_data(csv_file_path)

In [83]:
def load_data(csv_path):
    conn = db_connection()
    cursor = conn.cursor()
    with open(csv_path, 'r') as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                           INSERT INTO yanki.Products(Product_ID, Product_Name, Brand, Category, Price)
                            VALUES (%s,%s,%s,%s,%s);''',
                            row
                           
                           
                        )
    conn.commit()
    cursor.close()
    conn.close()
    
csv_file_path = r'dataset\cleaneddata\ Products.csv'
load_data(csv_file_path)

In [89]:
def load_data(csv_path):
    conn =db_connection()
    cursor = conn.cursor()
    with open (csv_path, 'r') as file:
        reader =csv.reader(file)
        next(reader)
        for row in reader:
            cursor.execute('''
                            insert into yanki.Orders(Order_ID, Customer_ID, Product_ID, Quantity, Total_Price, Order_Date)
                        values(%s,%s,%s,%s,%s,%s);''',
                        row
                        )
    conn.commit()
    cursor.close()
    conn.close()

csv_file_path = r'dataset\cleaneddata\ Orders.csv'
load_data(csv_file_path)

In [97]:
def load_csv_data(csv_path):
    conn = db_connection()
    cursor = conn.cursor()
    with open (csv_path, 'r') as file:
        readers = csv.reader(file)
        next(readers)
        for row in readers:
            cursor.execute('''
                        insert into yanki.payment(Order_ID, Phone_Number, Payment_Method, Transaction_Status)
                        values(%s,%s,%s,%s);''',
                        row
                        )
    conn.commit()
    cursor.close()
    conn.close()

csv_location = r'dataset\cleaneddata\ Payment.csv'
load_csv_data(csv_location)

In [101]:
def load_file(csv_path):
    conn= db_connection()
    cursor = conn.cursor()
    with open (csv_path, 'r') as file:
        readers =csv.reader(file)
        next(readers)
        for row in readers:
            cursor.execute('''
                            insert into yanki.shipping(Customer_ID, Shipping_Address, City, State, Country, Postal_Code)
                           values(%s,%s,%s,%s,%s,%s);''',
                           row
                        )
    conn.commit()
    cursor.close()
    conn.close()
path_of_csv = r'dataset\cleaneddata\ Shipping_Details.csv'
load_file(path_of_csv)

In [98]:
display(shipping_df.columns)

Index(['Customer_ID', 'Shipping_Address', 'City', 'State', 'Country',
       'Postal_Code'],
      dtype='object')

In [68]:
Customer_df

,Customer_ID,Customer_Name,Email,Phone_Number
0,e0d6cb3c-c4b0-4cfe-8225-b65d094d2424,Dominic Buchanan,margaret97@example.com,259.603.6134
1,fa3ca35a-5540-404b-a7eb-9001cdcbd840,Daniel Allen,angela55@example.com,+1-869-659-4272x982
2,7ad4de53-e6d7-4cd3-99b8-13fb70fe7a34,Daniel Schmidt,wayne59@example.org,292.840.0975x724
3,4b9b409c-19f2-41c0-bc7c-6556e0647ebb,John Gonzalez,qsherman@example.com,+1-643-561-3912x262
4,81b513ad-5c02-48cf-bff0-39e1440c4d22,Amber Benitez,derek85@example.com,3424148376
...,...,...,...,...
985,1e75eb3a-9ba5-4ea6-82ec-886abe298058,Jeremy Farrell,leejohn@example.com,922.207.8157x85481
986,c53c32ef-2e64-4ac4-ac48-3707ab1ebd1f,Marc Hudson,james85@example.org,908.901.4896x12666
987,ebc19a03-a32d-4d3c-9976-f30cee3d3a70,Devin Joseph,chadbenson@example.com,(718)789-6289
988,0598403f-7a42-44a9-994e-9f23feb20394,Spencer Elliott,eric98@example.org,366-506-0469x728
989,8832dd24-c104-475b-8327-d687d3912b58,Jeffrey Jackson,turnerjoanna@example.org,8483263716